export const auth = {
    REGISTER: 'REGISTER',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
};

export const setting = {
    SEARCH_CATEGORY: 'SEARCH_CATEGORY',
    SEARCH_CATEGORY_SUCCESS: 'SEARCH_CATEGORY_SUCCESS',
    SEARCH_CATEGORY_FAILURE: 'SEARCH_CATEGORY_FAILURE'
}
